-- SPDX-License-Identifier: ISC
-- sh/compound_test.lua: tests for compound commands

local function sh(input)
	local src = debug.getinfo(1, "S").source:match("^@(.+/)")
	local cmd = string.format("lua5.4 %ssh.lua -c '%s' 2>/dev/null", src, input:gsub("'", "'\\''"))
	local f = io.popen(cmd)
	local out = f:read("*a"):gsub("\n$", "")
	f:close()
	return out
end

describe("compound commands", function()
	describe("if/then/fi", function()
		it("executes then branch on true", function()
			assert.equal("yes", sh("if true; then echo yes; fi"))
		end)
		it("skips then branch on false", function()
			assert.equal("", sh("if false; then echo yes; fi"))
		end)
		it("executes else branch on false", function()
			assert.equal("no", sh("if false; then echo yes; else echo no; fi"))
		end)
		it("elif", function()
			assert.equal("two", sh("if false; then echo one; elif true; then echo two; else echo three; fi"))
		end)
		it("nested if", function()
			assert.equal("inner", sh("if true; then if true; then echo inner; fi; fi"))
		end)
	end)

	describe("while/do/done", function()
		it("loops while condition is true", function()
			assert.equal("3 2 1", sh("x=3; while [ $x -gt 0 ]; do echo $x; x=$(expr $x - 1); done"):gsub("\n", " "))
		end)
		it("does not execute body if condition is false", function()
			assert.equal("", sh("while false; do echo no; done"))
		end)
	end)

	describe("for/in/do/done", function()
		it("iterates over word list", function()
			assert.equal("a b c", sh("for i in a b c; do echo $i; done"):gsub("\n", " "))
		end)
		it("empty list does not execute body", function()
			assert.equal("", sh("for i in; do echo $i; done"))
		end)
	end)
end)
