-- SPDX-License-Identifier: ISC
local t = require("sh.test")

describe("sh.test", function()
	describe("0 args", function()
		it("returns false", function()
			assert.is_false(t.eval({}))
		end)
	end)

	describe("1 arg", function()
		it("non-empty string is true", function()
			assert.is_true(t.eval({ "hello" }))
		end)
		it("empty string is false", function()
			assert.is_false(t.eval({ "" }))
		end)
	end)

	describe("string primaries", function()
		it("-n non-empty", function()
			assert.is_true(t.eval({ "-n", "hello" }))
		end)
		it("-n empty", function()
			assert.is_false(t.eval({ "-n", "" }))
		end)
		it("-z empty", function()
			assert.is_true(t.eval({ "-z", "" }))
		end)
		it("-z non-empty", function()
			assert.is_false(t.eval({ "-z", "hello" }))
		end)
		it("s1 = s2 equal", function()
			assert.is_true(t.eval({ "foo", "=", "foo" }))
		end)
		it("s1 = s2 not equal", function()
			assert.is_false(t.eval({ "foo", "=", "bar" }))
		end)
		it("s1 != s2", function()
			assert.is_true(t.eval({ "foo", "!=", "bar" }))
		end)
		it("s1 != s2 same", function()
			assert.is_false(t.eval({ "foo", "!=", "foo" }))
		end)
	end)

	describe("integer primaries", function()
		it("-eq", function()
			assert.is_true(t.eval({ "1", "-eq", "1" }))
			assert.is_false(t.eval({ "1", "-eq", "2" }))
		end)
		it("-ne", function()
			assert.is_true(t.eval({ "1", "-ne", "2" }))
		end)
		it("-lt", function()
			assert.is_true(t.eval({ "1", "-lt", "2" }))
			assert.is_false(t.eval({ "2", "-lt", "1" }))
		end)
		it("-le", function()
			assert.is_true(t.eval({ "2", "-le", "2" }))
		end)
		it("-gt", function()
			assert.is_true(t.eval({ "3", "-gt", "2" }))
		end)
		it("-ge", function()
			assert.is_true(t.eval({ "2", "-ge", "2" }))
			assert.is_true(t.eval({ "3", "-ge", "2" }))
		end)
	end)

	describe("file primaries", function()
		it("-e existing", function()
			assert.is_true(t.eval({ "-e", "/etc/passwd" }))
		end)
		it("-e non-existing", function()
			assert.is_false(t.eval({ "-e", "/nonexistent_xyz" }))
		end)
		it("-f regular file", function()
			assert.is_true(t.eval({ "-f", "/etc/passwd" }))
		end)
		it("-f directory", function()
			assert.is_false(t.eval({ "-f", "/tmp" }))
		end)
		it("-d directory", function()
			assert.is_true(t.eval({ "-d", "/tmp" }))
		end)
		it("-r readable", function()
			assert.is_true(t.eval({ "-r", "/etc/passwd" }))
		end)
		it("-s non-empty", function()
			assert.is_true(t.eval({ "-s", "/etc/passwd" }))
		end)
		it("-x executable", function()
			assert.is_true(t.eval({ "-x", "/bin/sh" }))
		end)
	end)

	describe("negation", function()
		it("! non-empty -> false", function()
			assert.is_false(t.eval({ "!", "hello" }))
		end)
		it("! empty -> true", function()
			assert.is_true(t.eval({ "!", "" }))
		end)
		it("! 3-arg binary", function()
			assert.is_false(t.eval({ "!", "1", "-eq", "1" }))
			assert.is_true(t.eval({ "!", "1", "-eq", "2" }))
		end)
	end)

	describe("[ form", function()
		it("strips trailing ]", function()
			assert.is_true(t.eval({ "hello", "]" }))
			assert.is_true(t.eval({ "foo", "=", "foo", "]" }))
		end)
	end)
end)
