-- SPDX-License-Identifier: ISC
-- sh/vars_test.lua
local env = require("sh.env")
local expand = require("sh.expand")

describe("sh.env", function()
	before_each(function()
		env.reset()
	end)

	describe("variable assignment", function()
		it("sets and gets a variable", function()
			env.set("FOO", "bar")
			assert.equal("bar", env.get("FOO"))
		end)

		it("unset removes a variable", function()
			env.set("FOO", "bar")
			env.unset("FOO")
			assert.is_nil(env.get("FOO"))
		end)

		it("export marks variable for export", function()
			env.set("FOO", "bar")
			env.export("FOO")
			assert.is_true(env.is_exported("FOO"))
		end)

		it("unexported variable is not exported", function()
			local name = "_SH_TEST_" .. tostring(math.random(100000, 999999))
			env.set(name, "bar")
			assert.is_false(env.is_exported(name))
		end)

		it("unset also clears export flag", function()
			env.set("FOO", "bar")
			env.export("FOO")
			env.unset("FOO")
			assert.is_false(env.is_exported("FOO"))
		end)

		it("inherits from process environment", function()
			-- HOME should be set from the real environment
			assert.is_string(env.get("HOME"))
		end)
	end)

	describe("special parameters", function()
		it("$? reflects last exit status", function()
			env.set_status(42)
			assert.equal("42", env.get("?"))
		end)

		it("$$ is the shell PID", function()
			local pid = env.get("$")
			assert.is_string(pid)
			assert.is_true(tonumber(pid) > 0)
		end)

		it("$0 is the shell name", function()
			env.set_argv({ "sh", "a", "b", "c" })
			assert.equal("sh", env.get("0"))
		end)

		it("$# is the count of positional parameters", function()
			env.set_argv({ "sh", "a", "b", "c" })
			assert.equal("3", env.get("#"))
		end)

		it("$@ expands to all positional parameters space-joined", function()
			env.set_argv({ "sh", "a", "b", "c" })
			assert.equal("a b c", env.get("@"))
		end)

		it("$* expands to all positional parameters space-joined", function()
			env.set_argv({ "sh", "a", "b", "c" })
			assert.equal("a b c", env.get("*"))
		end)

		it("$! is empty when no background job run", function()
			assert.equal("", env.get("!"))
		end)

		it("$- is empty (no option flags implemented)", function()
			assert.equal("", env.get("-"))
		end)
	end)
end)

describe("sh.expand", function()
	before_each(function()
		env.reset()
	end)

	it("expands $VAR", function()
		env.set("FOO", "hello")
		assert.equal("hello", expand.word("$FOO"))
	end)

	it("expands ${VAR}", function()
		env.set("FOO", "world")
		assert.equal("world", expand.word("${FOO}"))
	end)

	it("unset variable expands to empty string", function()
		assert.equal("", expand.word("$UNSET_XYZ"))
	end)

	it("expands $? to last status", function()
		env.set_status(1)
		assert.equal("1", expand.word("$?"))
	end)

	it("expands $$ to shell PID", function()
		local pid = expand.word("$$")
		assert.is_true(tonumber(pid) > 0)
	end)

	it("expands mixed text and variable", function()
		env.set("NAME", "world")
		assert.equal("hello world", expand.word("hello $NAME"))
	end)

	it("does not expand inside single quotes", function()
		env.set("FOO", "bar")
		assert.equal("$FOO", expand.word("'$FOO'"))
	end)

	it("expands inside double quotes", function()
		env.set("FOO", "bar")
		assert.equal("bar", expand.word('"$FOO"'))
	end)

	it("is_assignment detects NAME=value", function()
		assert.is_truthy(expand.is_assignment("FOO=bar"))
		assert.is_falsy(expand.is_assignment("echo"))
		assert.is_falsy(expand.is_assignment("=bar"))
	end)

	it("parse_assignment splits NAME=value", function()
		local name, val = expand.parse_assignment("FOO=hello world")
		assert.equal("FOO", name)
		assert.equal("hello world", val)
	end)

	describe("${var:-word} use default", function()
		it("returns value when set and non-null", function()
			env.set("X", "hello")
			assert.equal("hello", expand.word("${X:-default}"))
		end)
		it("returns word when unset", function()
			assert.equal("default", expand.word("${X:-default}"))
		end)
		it("returns word when null", function()
			env.set("X", "")
			assert.equal("default", expand.word("${X:-default}"))
		end)
		it("returns empty when word omitted and unset", function()
			assert.equal("", expand.word("${X:-}"))
		end)
	end)

	describe("${var-word} use default (unset only)", function()
		it("returns value when set and non-null", function()
			env.set("X", "hello")
			assert.equal("hello", expand.word("${X-default}"))
		end)
		it("returns word when unset", function()
			assert.equal("default", expand.word("${X-default}"))
		end)
		it("returns null when set but null", function()
			env.set("X", "")
			assert.equal("", expand.word("${X-default}"))
		end)
	end)

	describe("${var:=word} assign default", function()
		it("returns value when set and non-null", function()
			env.set("X", "hello")
			assert.equal("hello", expand.word("${X:=default}"))
			assert.equal("hello", env.get("X"))
		end)
		it("assigns and returns word when unset", function()
			assert.equal("default", expand.word("${X:=default}"))
			assert.equal("default", env.get("X"))
		end)
		it("assigns and returns word when null", function()
			env.set("X", "")
			assert.equal("default", expand.word("${X:=default}"))
			assert.equal("default", env.get("X"))
		end)
	end)

	describe("${var=word} assign default (unset only)", function()
		it("returns value when set", function()
			env.set("X", "hello")
			assert.equal("hello", expand.word("${X=default}"))
		end)
		it("assigns and returns word when unset", function()
			assert.equal("default", expand.word("${X=default}"))
			assert.equal("default", env.get("X"))
		end)
		it("returns null when set but null", function()
			env.set("X", "")
			assert.equal("", expand.word("${X=default}"))
		end)
	end)

	describe("${var:+word} use alternative", function()
		it("returns word when set and non-null", function()
			env.set("X", "hello")
			assert.equal("alt", expand.word("${X:+alt}"))
		end)
		it("returns null when unset", function()
			assert.equal("", expand.word("${X:+alt}"))
		end)
		it("returns null when null", function()
			env.set("X", "")
			assert.equal("", expand.word("${X:+alt}"))
		end)
	end)

	describe("${var+word} use alternative (set only)", function()
		it("returns word when set and non-null", function()
			env.set("X", "hello")
			assert.equal("alt", expand.word("${X+alt}"))
		end)
		it("returns word when set but null", function()
			env.set("X", "")
			assert.equal("alt", expand.word("${X+alt}"))
		end)
		it("returns null when unset", function()
			assert.equal("", expand.word("${X+alt}"))
		end)
	end)

	describe("${var:?word} error if null/unset", function()
		it("returns value when set and non-null", function()
			env.set("X", "hello")
			assert.equal("hello", expand.word("${X:?errmsg}"))
		end)
		it("returns empty and writes error when unset", function()
			assert.equal("", expand.word("${X:?errmsg}"))
		end)
		it("returns empty and writes error when null", function()
			env.set("X", "")
			assert.equal("", expand.word("${X:?errmsg}"))
		end)
	end)

	describe("${var?word} error if unset", function()
		it("returns value when set", function()
			env.set("X", "hello")
			assert.equal("hello", expand.word("${X?errmsg}"))
		end)
		it("returns null when set but null", function()
			env.set("X", "")
			assert.equal("", expand.word("${X?errmsg}"))
		end)
		it("returns empty and writes error when unset", function()
			assert.equal("", expand.word("${X?errmsg}"))
		end)
	end)

	describe("${#var} string length", function()
		it("returns length of value", function()
			env.set("X", "hello")
			assert.equal("5", expand.word("${#X}"))
		end)
		it("returns 0 for unset", function()
			assert.equal("0", expand.word("${#X}"))
		end)
		it("returns 0 for empty", function()
			env.set("X", "")
			assert.equal("0", expand.word("${#X}"))
		end)
	end)

	describe("${var%pattern} remove smallest suffix", function()
		it("removes suffix", function()
			env.set("X", "file.c")
			assert.equal("file", expand.word("${X%.c}"))
		end)
		it("removes smallest suffix with glob", function()
			env.set("X", "a/b/c")
			assert.equal("a/b", expand.word("${X%/*}"))
		end)
		it("no match returns original", function()
			env.set("X", "file.c")
			assert.equal("file.c", expand.word("${X%.o}"))
		end)
	end)

	describe("${var%%pattern} remove largest suffix", function()
		it("removes largest suffix with glob", function()
			env.set("X", "a/b/c")
			assert.equal("a", expand.word("${X%%/*}"))
		end)
		it("simple pattern same as %", function()
			env.set("X", "file.c")
			assert.equal("file", expand.word("${X%%.c}"))
		end)
	end)

	describe("${var#pattern} remove smallest prefix", function()
		it("removes prefix", function()
			env.set("X", "/usr/bin")
			assert.equal("usr/bin", expand.word("${X#/}"))
		end)
		it("removes smallest prefix with glob", function()
			env.set("X", "/one/two/three")
			assert.equal("two/three", expand.word("${X#/*/}"))
		end)
		it("no match returns original", function()
			env.set("X", "hello")
			assert.equal("hello", expand.word("${X#x}"))
		end)
	end)

	describe("${var##pattern} remove largest prefix", function()
		it("removes largest prefix with glob", function()
			env.set("X", "/one/two/three")
			assert.equal("three", expand.word("${X##*/}"))
		end)
		it("simple pattern same as #", function()
			env.set("X", "/usr/bin")
			assert.equal("usr/bin", expand.word("${X##/}"))
		end)
	end)

	describe("nested parameter expansion", function()
		it("expands variables in word part", function()
			env.set("D", "fallback")
			assert.equal("fallback", expand.word("${X:-$D}"))
		end)
		it("nested ${} in word", function()
			env.set("Y", "inner")
			assert.equal("inner", expand.word("${X:-${Y}}"))
		end)
	end)
end)
