-- SPDX-License-Identifier: ISC
-- make/parser_test.lua - busted tests for the makefile parser
local parser = require("make.parser")

describe("parser.parse", function()
	it("parses a simple rule", function()
		local nodes = parser.parse("all: main.o\n\tgcc -o all main.o\n")
		assert.equals("rule", nodes[1].type)
		assert.same({ "all" }, nodes[1].targets)
		assert.same({ "main.o" }, nodes[1].prerequisites)
		assert.equals("gcc -o all main.o", nodes[1].recipes[1])
	end)

	it("parses variable assignment =", function()
		local nodes = parser.parse("CC = gcc\n")
		assert.equals("assign", nodes[1].type)
		assert.equals("CC", nodes[1].name)
		assert.equals("=", nodes[1].op)
		assert.equals("gcc", nodes[1].value)
	end)

	it("parses := assignment", function()
		local nodes = parser.parse("CC := clang\n")
		assert.equals("assign", nodes[1].type)
		assert.equals(":=", nodes[1].op)
		assert.equals("clang", nodes[1].value)
	end)

	it("parses += assignment", function()
		local nodes = parser.parse("CFLAGS += -Wall\n")
		assert.equals("assign", nodes[1].type)
		assert.equals("+=", nodes[1].op)
		assert.equals("-Wall", nodes[1].value)
	end)

	it("parses ?= assignment", function()
		local nodes = parser.parse("CC ?= gcc\n")
		assert.equals("assign", nodes[1].type)
		assert.equals("?=", nodes[1].op)
	end)

	it("parses multiple prerequisites", function()
		local nodes = parser.parse("all: foo.o bar.o baz.o\n")
		assert.same({ "foo.o", "bar.o", "baz.o" }, nodes[1].prerequisites)
	end)

	it("parses multiple targets", function()
		local nodes = parser.parse("foo bar: dep\n")
		assert.same({ "foo", "bar" }, nodes[1].targets)
	end)

	it("parses inline recipe after semicolon", function()
		local nodes = parser.parse("all: ; @echo done\n")
		assert.equals("rule", nodes[1].type)
		assert.equals("@echo done", nodes[1].recipes[1])
	end)

	it("parses multiple recipe lines", function()
		local nodes = parser.parse("all:\n\techo one\n\techo two\n\techo three\n")
		assert.equals(3, #nodes[1].recipes)
		assert.equals("echo one", nodes[1].recipes[1])
		assert.equals("echo three", nodes[1].recipes[3])
	end)

	it("collapses backslash-newline in non-recipe lines", function()
		local nodes = parser.parse("SRCS = a.c \\\n  b.c \\\n  c.c\n")
		assert.equals("assign", nodes[1].type)
		-- continuation lines joined with space; leading whitespace from next line preserved
		assert.truthy(nodes[1].value:find("a%.c"))
		assert.truthy(nodes[1].value:find("b%.c"))
		assert.truthy(nodes[1].value:find("c%.c"))
	end)

	it("preserves backslash-newline in recipe lines", function()
		local nodes = parser.parse("all:\n\tfor x in a b; do \\\n\t\techo $$x; \\\n\tdone\n")
		-- Should be a single recipe with embedded newlines
		assert.equals(1, #nodes[1].recipes)
		assert.truthy(nodes[1].recipes[1]:find("\n"))
	end)

	it("strips comments", function()
		local nodes = parser.parse("CC = gcc # the compiler\n")
		assert.equals("assign", nodes[1].type)
		assert.equals("gcc", nodes[1].value:match("^(.-)%s*$"))
	end)

	it("detects inference rules", function()
		local nodes = parser.parse(".c.o:\n\t$(CC) -c $<\n")
		assert.equals("rule", nodes[1].type)
		assert.is_true(nodes[1].inference)
	end)

	it("detects single-suffix inference rules", function()
		local nodes = parser.parse(".c:\n\t$(CC) -o $@ $<\n")
		assert.equals("rule", nodes[1].type)
		assert.is_true(nodes[1].inference)
	end)

	it("does not treat .PHONY as inference rule", function()
		local nodes = parser.parse(".PHONY: all clean\n")
		assert.equals("rule", nodes[1].type)
		assert.is_false(nodes[1].inference)
	end)

	it("parses double-colon rules", function()
		local nodes = parser.parse("all:: foo\n")
		assert.is_true(nodes[1].double_colon)
	end)

	it("parses include directive", function()
		local nodes = parser.parse("include config.mk\n")
		assert.equals("include", nodes[1].type)
		assert.equals("config.mk", nodes[1].arg)
	end)

	it("parses -include directive", function()
		local nodes = parser.parse("-include deps.mk\n")
		assert.equals("include", nodes[1].type)
		assert.equals("-include", nodes[1].keyword)
	end)

	it("parses ifdef conditional", function()
		local nodes = parser.parse("ifdef FOO\nCC = gcc\nendif\n")
		assert.equals("conditional", nodes[1].type)
		assert.equals("ifdef", nodes[1].keyword)
		assert.equals("assign", nodes[2].type)
		assert.equals("endif", nodes[3].type)
	end)

	it("parses pattern rules", function()
		local nodes = parser.parse("%.o: %.c\n\t$(CC) -c $<\n")
		assert.same({ "%.o" }, nodes[1].targets)
		assert.same({ "%.c" }, nodes[1].prerequisites)
	end)
end)
