-- SPDX-License-Identifier: ISC
-- tar/format_test.lua - busted tests for tar format encoder/decoder
local format = require("tar.format")
local unistd = require("posix.unistd")
local fcntl = require("posix.fcntl")

describe("tar format", function()
	describe("encode_header", function()
		it("produces a 512-byte block", function()
			local hdr = format.encode_header({ name = "test.txt", size = 0, mode = 420, typeflag = "0" })
			assert.equals(512, #hdr)
		end)

		it("encodes name correctly", function()
			local hdr = format.encode_header({ name = "hello.txt", size = 100, mode = 420 })
			assert.equals("hello.txt", hdr:sub(1, 9))
		end)

		it("sets ustar magic", function()
			local hdr = format.encode_header({ name = "x", size = 0 })
			assert.equals("ustar", hdr:sub(258, 262))
		end)
	end)

	describe("decode_header", function()
		it("round-trips a header", function()
			local orig = { name = "dir/file.txt", mode = 493, uid = 1000, gid = 1000,
				size = 42, mtime = 1700000000, typeflag = "0",
				uname = "user", gname = "group" }
			local block = format.encode_header(orig)
			local decoded = format.decode_header(block)
			assert.equals("dir/file.txt", decoded.name)
			assert.equals(493, decoded.mode)
			assert.equals(1000, decoded.uid)
			assert.equals(1000, decoded.gid)
			assert.equals(42, decoded.size)
			assert.equals(1700000000, decoded.mtime)
			assert.equals("0", decoded.typeflag)
			assert.equals("user", decoded.uname)
			assert.equals("group", decoded.gname)
		end)

		it("returns nil for zero block (EOF)", function()
			local block = string.rep("\0", 512)
			assert.is_nil(format.decode_header(block))
		end)

		it("handles directory typeflag", function()
			local block = format.encode_header({ name = "mydir/", typeflag = "5", mode = 493 })
			local decoded = format.decode_header(block)
			assert.equals("5", decoded.typeflag)
			assert.equals("mydir/", decoded.name)
		end)

		it("handles symlink", function()
			local block = format.encode_header({ name = "link", typeflag = "2", linkname = "target" })
			local decoded = format.decode_header(block)
			assert.equals("2", decoded.typeflag)
			assert.equals("target", decoded.linkname)
		end)

		it("handles long names via prefix", function()
			local long = "a/very/long/path/that/exceeds/one/hundred/characters/in/total/length/to/test/prefix/splitting/file.txt"
			local block = format.encode_header({ name = long, size = 0 })
			local decoded = format.decode_header(block)
			assert.equals(long, decoded.name)
		end)
	end)

	describe("pad_data", function()
		it("pads to 512 boundary", function()
			assert.equals(512, #format.pad_data("hello"))
		end)
		it("does not pad exact multiple", function()
			local data = string.rep("x", 512)
			assert.equals(512, #format.pad_data(data))
		end)
		it("pads 513 bytes to 1024", function()
			local data = string.rep("x", 513)
			assert.equals(1024, #format.pad_data(data))
		end)
	end)

	describe("read/write entry", function()
		it("round-trips an entry through a file", function()
			local tmp = os.tmpname()
			local fd = fcntl.open(tmp, fcntl.O_WRONLY + fcntl.O_CREAT + fcntl.O_TRUNC, 420)
			local data = "Hello, tar world!\n"
			format.write_entry(fd, { name = "greeting.txt", size = #data, mode = 420, typeflag = "0" }, data)
			unistd.write(fd, format.eof_marker())
			unistd.close(fd)

			fd = fcntl.open(tmp, fcntl.O_RDONLY)
			local hdr, content = format.read_entry(fd)
			unistd.close(fd)
			os.remove(tmp)

			assert.equals("greeting.txt", hdr.name)
			assert.equals(#data, hdr.size)
			assert.equals(data, content)
		end)

		it("reads multiple entries", function()
			local tmp = os.tmpname()
			local fd = fcntl.open(tmp, fcntl.O_WRONLY + fcntl.O_CREAT + fcntl.O_TRUNC, 420)
			format.write_entry(fd, { name = "a.txt", size = 3, mode = 420 }, "aaa")
			format.write_entry(fd, { name = "b.txt", size = 3, mode = 420 }, "bbb")
			unistd.write(fd, format.eof_marker())
			unistd.close(fd)

			fd = fcntl.open(tmp, fcntl.O_RDONLY)
			local h1, d1 = format.read_entry(fd)
			local h2, d2 = format.read_entry(fd)
			local h3 = format.read_entry(fd)
			unistd.close(fd)
			os.remove(tmp)

			assert.equals("a.txt", h1.name)
			assert.equals("aaa", d1)
			assert.equals("b.txt", h2.name)
			assert.equals("bbb", d2)
			assert.is_nil(h3)
		end)
	end)
end)
